user_booking_ticket
MartaSolo/montecinema pull request #8
Opened 2022-10-03 07:25 UTC by MartaSolo

- booking ticket functionality for a user with styling for desktop, mobile;
- plus small changes in other components / utils etc.
<img width="730" alt="step 1 - desktop" src="https://user-images.githubusercontent.com/90101598/193522222-9c7bd5d1-6a19-492a-9427-b940ebe54a10.png">
<img width="728" alt="step 2 - dekstop" src="https://user-images.githubusercontent.com/90101598/193522230-dd50cb03-883c-4f44-bb2d-3b5eb16bdfe5.png">
<img width="216" alt="step 2 - mobile" src="https://user-images.githubusercontent.com/90101598/193522232-759314c7-1319-4670-aa1c-3bbd1cb74b64.png">
<img width="798" alt="step 3 - desktop" src="https://user-images.githubusercontent.com/90101598/193522234-e3606b2e-cf1e-4133-beca-cce967324798.png">
<img width="217" alt="step 3 - mobile" src="https://user-images.githubusercontent.com/90101598/193522237-8b9277ac-ea91-48eb-9923-cf4f4dd111fe.png">

2022-10-03 11:26 UTC, szymonlicau requested changes

2022-10-03 11:26 UTC, szymonlicau commented on src/components/booking/BookingSuccess.vue
> +import BaseButton from "../global/BaseButton.vue";
We should stick to using the aliases everywhere 😄

```suggestion
import BaseButton from "@/components/global/BaseButton.vue";
```

2022-10-03 11:26 UTC, szymonlicau commented on src/components/booking/BookingSuccess.vue
> +});
Why not simply name it `reservationId`? Computed is not a function in itself so the `get` part is kind of strange 😄 
```suggestion
const reservationId = computed(() => {
  return reservedSeance.value?.id;
});
```

2022-10-03 11:26 UTC, szymonlicau commented on src/components/booking/BookingSuccess.vue
> +const getReservationData = () => {
Same with this one
```suggestion
const reservationData = () => {
```

2022-10-03 11:26 UTC, szymonlicau commented on src/components/booking/BookingSuccess.vue
> +const getSubtitle = () => {
And these two

2022-10-03 11:26 UTC, szymonlicau commented on src/components/booking/ChooseSeats.vue
> +interface chosenSeat {
We should write our types in `PascalCase` to let them stand out and be consistent 😄 
```suggestion
interface ChosenSeat {
```

2022-10-03 11:26 UTC, szymonlicau commented on src/components/booking/ChooseTickets.vue
> +const terms: Ref<boolean> = ref(false);
No need to be *that* explicit - if we pass a boolean value, TypeScript will know everything :)
```suggestion
const terms = ref(false);
```

2022-10-03 11:26 UTC, szymonlicau commented on src/components/booking/ChooseTickets.vue
> +  }
```suggestion
  } else {
    router.push({ name: "UserLogIn" });
  }
```

2022-10-03 11:26 UTC, szymonlicau commented on src/i18n.ts
> +  fallbackLocale: "en-GB",
Why the change from `en` to `en-GB`? 🤔

2022-10-03 11:26 UTC, szymonlicau commented on src/pages/BookTicket.vue
> +const step: Ref<number> = ref(1);
TypeScript should infer that one properly 🤔 
```suggestion
const step = ref(1);
```

2022-10-03 11:26 UTC, szymonlicau commented on src/utils/hall.js
> +export const hallPlan = (array) => {
Likewise for these function, argument names like `array` are too generic! We should give more hints to what's going on here 😄

2022-10-03 18:42 UTC, MartaSolo commented on src/i18n.ts
> +  fallbackLocale: "en-GB",
to get the right format data

2022-10-04 07:24 UTC, szymonlicau approved these changes

2022-10-04 09:57 UTC, merged